version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 3

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 3
